In [1]:
import numpy as np
import pandas as pd
import os
import csv
import cv2
from sklearn.cluster import KMeans
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
from sklearn.tree import DecisionTreeClassifier
import sklearn.metrics as metrics
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import Normalizer

In [2]:
folder1=r"D:\CV_datasets\370x370\crowded"
folder2=r"D:\CV_datasets\370x370\Non-crowded"

In [3]:
i=0
for filename in os.listdir(folder1):
    #path
    path=os.path.join(folder1,filename)
    a=cv2.imread(path)
    if a is None:
        continue
    
    #resize image
    resize=(100,300)
    img=cv2.resize(a,resize)
    
    resultimage = np.zeros((100, 300))
   
    #normalizing the given image using normalize() function
    nimg = cv2.normalize(img,resultimage, 0, 255, cv2.NORM_MINMAX)
    
    #gray image
    gray = cv2.cvtColor(nimg, cv2.COLOR_BGR2GRAY)
    hist_image=cv2.equalizeHist(gray)
    
    
    #initialise sift descriptor
    sift=cv2.xfeatures2d.SIFT_create()
    keypoints, descriptors = sift.detectAndCompute(hist_image, None)
    
    
    #convert the descriptor array into a dataframe format
    out=pd.DataFrame(descriptors)
    print("descriptor shape ",i," : ", out.shape)
    i=i+1
    
    #drop first coloumn as it's the no of feature detected. Not required.
    #append to the csv file
    csv_data=out.to_csv(r'D:\CV_datasets\370x370\crowded.csv', mode='a', header=False,index=False)

descriptor shape  0  :  (279, 128)
descriptor shape  1  :  (184, 128)
descriptor shape  2  :  (297, 128)
descriptor shape  3  :  (364, 128)
descriptor shape  4  :  (435, 128)
descriptor shape  5  :  (353, 128)
descriptor shape  6  :  (364, 128)
descriptor shape  7  :  (251, 128)
descriptor shape  8  :  (269, 128)
descriptor shape  9  :  (485, 128)
descriptor shape  10  :  (334, 128)
descriptor shape  11  :  (299, 128)
descriptor shape  12  :  (302, 128)
descriptor shape  13  :  (278, 128)
descriptor shape  14  :  (333, 128)
descriptor shape  15  :  (442, 128)
descriptor shape  16  :  (354, 128)
descriptor shape  17  :  (319, 128)
descriptor shape  18  :  (230, 128)
descriptor shape  19  :  (297, 128)
descriptor shape  20  :  (162, 128)
descriptor shape  21  :  (182, 128)
descriptor shape  22  :  (360, 128)
descriptor shape  23  :  (379, 128)
descriptor shape  24  :  (229, 128)
descriptor shape  25  :  (325, 128)
descriptor shape  26  :  (312, 128)
descriptor shape  27  :  (262, 128)
de

descriptor shape  227  :  (345, 128)
descriptor shape  228  :  (498, 128)
descriptor shape  229  :  (251, 128)
descriptor shape  230  :  (160, 128)
descriptor shape  231  :  (392, 128)
descriptor shape  232  :  (225, 128)
descriptor shape  233  :  (453, 128)
descriptor shape  234  :  (381, 128)
descriptor shape  235  :  (235, 128)
descriptor shape  236  :  (218, 128)
descriptor shape  237  :  (249, 128)
descriptor shape  238  :  (123, 128)
descriptor shape  239  :  (165, 128)
descriptor shape  240  :  (200, 128)
descriptor shape  241  :  (397, 128)
descriptor shape  242  :  (316, 128)
descriptor shape  243  :  (341, 128)
descriptor shape  244  :  (203, 128)
descriptor shape  245  :  (380, 128)
descriptor shape  246  :  (241, 128)
descriptor shape  247  :  (172, 128)
descriptor shape  248  :  (486, 128)
descriptor shape  249  :  (156, 128)
descriptor shape  250  :  (171, 128)
descriptor shape  251  :  (223, 128)
descriptor shape  252  :  (139, 128)
descriptor shape  253  :  (501, 128)
d

descriptor shape  450  :  (209, 128)
descriptor shape  451  :  (189, 128)
descriptor shape  452  :  (201, 128)
descriptor shape  453  :  (421, 128)
descriptor shape  454  :  (240, 128)
descriptor shape  455  :  (278, 128)
descriptor shape  456  :  (219, 128)
descriptor shape  457  :  (364, 128)
descriptor shape  458  :  (214, 128)
descriptor shape  459  :  (379, 128)
descriptor shape  460  :  (287, 128)
descriptor shape  461  :  (239, 128)
descriptor shape  462  :  (273, 128)
descriptor shape  463  :  (381, 128)
descriptor shape  464  :  (160, 128)
descriptor shape  465  :  (271, 128)
descriptor shape  466  :  (413, 128)
descriptor shape  467  :  (304, 128)
descriptor shape  468  :  (226, 128)
descriptor shape  469  :  (337, 128)
descriptor shape  470  :  (339, 128)
descriptor shape  471  :  (244, 128)
descriptor shape  472  :  (347, 128)
descriptor shape  473  :  (288, 128)
descriptor shape  474  :  (394, 128)
descriptor shape  475  :  (363, 128)
descriptor shape  476  :  (133, 128)
d

descriptor shape  675  :  (241, 128)
descriptor shape  676  :  (480, 128)
descriptor shape  677  :  (447, 128)
descriptor shape  678  :  (226, 128)
descriptor shape  679  :  (464, 128)
descriptor shape  680  :  (220, 128)
descriptor shape  681  :  (217, 128)
descriptor shape  682  :  (229, 128)
descriptor shape  683  :  (245, 128)
descriptor shape  684  :  (302, 128)
descriptor shape  685  :  (242, 128)
descriptor shape  686  :  (261, 128)
descriptor shape  687  :  (230, 128)
descriptor shape  688  :  (315, 128)
descriptor shape  689  :  (240, 128)
descriptor shape  690  :  (233, 128)
descriptor shape  691  :  (150, 128)
descriptor shape  692  :  (335, 128)
descriptor shape  693  :  (265, 128)
descriptor shape  694  :  (229, 128)
descriptor shape  695  :  (357, 128)
descriptor shape  696  :  (270, 128)
descriptor shape  697  :  (357, 128)
descriptor shape  698  :  (259, 128)
descriptor shape  699  :  (341, 128)
descriptor shape  700  :  (344, 128)
descriptor shape  701  :  (373, 128)
d

descriptor shape  897  :  (235, 128)
descriptor shape  898  :  (165, 128)
descriptor shape  899  :  (125, 128)
descriptor shape  900  :  (242, 128)
descriptor shape  901  :  (193, 128)
descriptor shape  902  :  (224, 128)
descriptor shape  903  :  (254, 128)
descriptor shape  904  :  (252, 128)
descriptor shape  905  :  (301, 128)
descriptor shape  906  :  (392, 128)
descriptor shape  907  :  (433, 128)
descriptor shape  908  :  (136, 128)
descriptor shape  909  :  (298, 128)
descriptor shape  910  :  (290, 128)
descriptor shape  911  :  (144, 128)
descriptor shape  912  :  (303, 128)
descriptor shape  913  :  (382, 128)
descriptor shape  914  :  (369, 128)
descriptor shape  915  :  (159, 128)
descriptor shape  916  :  (210, 128)
descriptor shape  917  :  (181, 128)
descriptor shape  918  :  (138, 128)
descriptor shape  919  :  (240, 128)
descriptor shape  920  :  (421, 128)
descriptor shape  921  :  (201, 128)
descriptor shape  922  :  (243, 128)
descriptor shape  923  :  (219, 128)
d

descriptor shape  1116  :  (355, 128)
descriptor shape  1117  :  (379, 128)
descriptor shape  1118  :  (213, 128)
descriptor shape  1119  :  (341, 128)
descriptor shape  1120  :  (360, 128)
descriptor shape  1121  :  (406, 128)
descriptor shape  1122  :  (359, 128)
descriptor shape  1123  :  (264, 128)
descriptor shape  1124  :  (384, 128)
descriptor shape  1125  :  (277, 128)
descriptor shape  1126  :  (206, 128)
descriptor shape  1127  :  (293, 128)
descriptor shape  1128  :  (234, 128)
descriptor shape  1129  :  (208, 128)
descriptor shape  1130  :  (355, 128)
descriptor shape  1131  :  (175, 128)
descriptor shape  1132  :  (180, 128)
descriptor shape  1133  :  (328, 128)
descriptor shape  1134  :  (357, 128)
descriptor shape  1135  :  (361, 128)
descriptor shape  1136  :  (368, 128)
descriptor shape  1137  :  (310, 128)
descriptor shape  1138  :  (114, 128)
descriptor shape  1139  :  (372, 128)
descriptor shape  1140  :  (341, 128)
descriptor shape  1141  :  (370, 128)
descriptor s

descriptor shape  1332  :  (284, 128)
descriptor shape  1333  :  (214, 128)
descriptor shape  1334  :  (267, 128)
descriptor shape  1335  :  (514, 128)
descriptor shape  1336  :  (234, 128)
descriptor shape  1337  :  (427, 128)
descriptor shape  1338  :  (330, 128)
descriptor shape  1339  :  (301, 128)
descriptor shape  1340  :  (416, 128)
descriptor shape  1341  :  (213, 128)
descriptor shape  1342  :  (270, 128)
descriptor shape  1343  :  (347, 128)
descriptor shape  1344  :  (325, 128)
descriptor shape  1345  :  (288, 128)
descriptor shape  1346  :  (406, 128)
descriptor shape  1347  :  (365, 128)
descriptor shape  1348  :  (278, 128)
descriptor shape  1349  :  (313, 128)
descriptor shape  1350  :  (354, 128)
descriptor shape  1351  :  (296, 128)
descriptor shape  1352  :  (157, 128)
descriptor shape  1353  :  (214, 128)
descriptor shape  1354  :  (348, 128)
descriptor shape  1355  :  (300, 128)
descriptor shape  1356  :  (291, 128)
descriptor shape  1357  :  (351, 128)
descriptor s

descriptor shape  1548  :  (383, 128)
descriptor shape  1549  :  (274, 128)
descriptor shape  1550  :  (323, 128)
descriptor shape  1551  :  (320, 128)
descriptor shape  1552  :  (407, 128)
descriptor shape  1553  :  (447, 128)
descriptor shape  1554  :  (260, 128)
descriptor shape  1555  :  (126, 128)
descriptor shape  1556  :  (318, 128)
descriptor shape  1557  :  (433, 128)
descriptor shape  1558  :  (346, 128)
descriptor shape  1559  :  (235, 128)
descriptor shape  1560  :  (319, 128)
descriptor shape  1561  :  (263, 128)
descriptor shape  1562  :  (162, 128)
descriptor shape  1563  :  (287, 128)
descriptor shape  1564  :  (271, 128)
descriptor shape  1565  :  (196, 128)
descriptor shape  1566  :  (327, 128)
descriptor shape  1567  :  (336, 128)
descriptor shape  1568  :  (155, 128)
descriptor shape  1569  :  (211, 128)
descriptor shape  1570  :  (208, 128)
descriptor shape  1571  :  (237, 128)
descriptor shape  1572  :  (254, 128)
descriptor shape  1573  :  (348, 128)
descriptor s

descriptor shape  1764  :  (344, 128)
descriptor shape  1765  :  (243, 128)
descriptor shape  1766  :  (350, 128)
descriptor shape  1767  :  (381, 128)
descriptor shape  1768  :  (294, 128)
descriptor shape  1769  :  (403, 128)
descriptor shape  1770  :  (316, 128)
descriptor shape  1771  :  (330, 128)
descriptor shape  1772  :  (417, 128)
descriptor shape  1773  :  (247, 128)
descriptor shape  1774  :  (332, 128)
descriptor shape  1775  :  (398, 128)
descriptor shape  1776  :  (322, 128)
descriptor shape  1777  :  (420, 128)
descriptor shape  1778  :  (153, 128)
descriptor shape  1779  :  (198, 128)
descriptor shape  1780  :  (290, 128)
descriptor shape  1781  :  (387, 128)
descriptor shape  1782  :  (394, 128)
descriptor shape  1783  :  (160, 128)
descriptor shape  1784  :  (283, 128)
descriptor shape  1785  :  (249, 128)
descriptor shape  1786  :  (433, 128)
descriptor shape  1787  :  (342, 128)
descriptor shape  1788  :  (233, 128)
descriptor shape  1789  :  (336, 128)
descriptor s

descriptor shape  1981  :  (273, 128)
descriptor shape  1982  :  (364, 128)
descriptor shape  1983  :  (268, 128)
descriptor shape  1984  :  (267, 128)
descriptor shape  1985  :  (340, 128)
descriptor shape  1986  :  (221, 128)
descriptor shape  1987  :  (399, 128)
descriptor shape  1988  :  (244, 128)
descriptor shape  1989  :  (109, 128)
descriptor shape  1990  :  (271, 128)
descriptor shape  1991  :  (296, 128)
descriptor shape  1992  :  (221, 128)
descriptor shape  1993  :  (427, 128)
descriptor shape  1994  :  (362, 128)
descriptor shape  1995  :  (247, 128)
descriptor shape  1996  :  (347, 128)
descriptor shape  1997  :  (408, 128)
descriptor shape  1998  :  (407, 128)
descriptor shape  1999  :  (391, 128)
descriptor shape  2000  :  (352, 128)
descriptor shape  2001  :  (173, 128)
descriptor shape  2002  :  (403, 128)
descriptor shape  2003  :  (222, 128)
descriptor shape  2004  :  (179, 128)
descriptor shape  2005  :  (339, 128)
descriptor shape  2006  :  (309, 128)
descriptor s

descriptor shape  2198  :  (233, 128)
descriptor shape  2199  :  (244, 128)
descriptor shape  2200  :  (327, 128)
descriptor shape  2201  :  (270, 128)
descriptor shape  2202  :  (157, 128)
descriptor shape  2203  :  (420, 128)
descriptor shape  2204  :  (138, 128)
descriptor shape  2205  :  (237, 128)
descriptor shape  2206  :  (456, 128)
descriptor shape  2207  :  (184, 128)
descriptor shape  2208  :  (150, 128)
descriptor shape  2209  :  (262, 128)
descriptor shape  2210  :  (274, 128)
descriptor shape  2211  :  (320, 128)
descriptor shape  2212  :  (160, 128)
descriptor shape  2213  :  (124, 128)
descriptor shape  2214  :  (508, 128)
descriptor shape  2215  :  (290, 128)
descriptor shape  2216  :  (201, 128)
descriptor shape  2217  :  (303, 128)
descriptor shape  2218  :  (315, 128)
descriptor shape  2219  :  (324, 128)
descriptor shape  2220  :  (459, 128)
descriptor shape  2221  :  (219, 128)
descriptor shape  2222  :  (178, 128)
descriptor shape  2223  :  (356, 128)
descriptor s

descriptor shape  2416  :  (370, 128)
descriptor shape  2417  :  (171, 128)
descriptor shape  2418  :  (241, 128)
descriptor shape  2419  :  (305, 128)
descriptor shape  2420  :  (213, 128)
descriptor shape  2421  :  (281, 128)
descriptor shape  2422  :  (391, 128)
descriptor shape  2423  :  (295, 128)
descriptor shape  2424  :  (177, 128)
descriptor shape  2425  :  (288, 128)
descriptor shape  2426  :  (250, 128)
descriptor shape  2427  :  (180, 128)
descriptor shape  2428  :  (340, 128)
descriptor shape  2429  :  (291, 128)
descriptor shape  2430  :  (288, 128)
descriptor shape  2431  :  (360, 128)
descriptor shape  2432  :  (350, 128)
descriptor shape  2433  :  (318, 128)
descriptor shape  2434  :  (204, 128)
descriptor shape  2435  :  (425, 128)
descriptor shape  2436  :  (269, 128)
descriptor shape  2437  :  (372, 128)
descriptor shape  2438  :  (178, 128)
descriptor shape  2439  :  (255, 128)
descriptor shape  2440  :  (316, 128)
descriptor shape  2441  :  (200, 128)
descriptor s

descriptor shape  2634  :  (380, 128)
descriptor shape  2635  :  (328, 128)
descriptor shape  2636  :  (176, 128)
descriptor shape  2637  :  (269, 128)
descriptor shape  2638  :  (176, 128)
descriptor shape  2639  :  (201, 128)
descriptor shape  2640  :  (116, 128)
descriptor shape  2641  :  (265, 128)
descriptor shape  2642  :  (243, 128)
descriptor shape  2643  :  (382, 128)
descriptor shape  2644  :  (226, 128)
descriptor shape  2645  :  (409, 128)
descriptor shape  2646  :  (345, 128)
descriptor shape  2647  :  (394, 128)
descriptor shape  2648  :  (423, 128)
descriptor shape  2649  :  (302, 128)
descriptor shape  2650  :  (197, 128)
descriptor shape  2651  :  (233, 128)
descriptor shape  2652  :  (212, 128)
descriptor shape  2653  :  (263, 128)
descriptor shape  2654  :  (146, 128)
descriptor shape  2655  :  (228, 128)
descriptor shape  2656  :  (245, 128)
descriptor shape  2657  :  (229, 128)
descriptor shape  2658  :  (297, 128)
descriptor shape  2659  :  (455, 128)
descriptor s

descriptor shape  2851  :  (315, 128)
descriptor shape  2852  :  (376, 128)
descriptor shape  2853  :  (314, 128)
descriptor shape  2854  :  (220, 128)
descriptor shape  2855  :  (194, 128)
descriptor shape  2856  :  (241, 128)
descriptor shape  2857  :  (333, 128)
descriptor shape  2858  :  (237, 128)
descriptor shape  2859  :  (276, 128)
descriptor shape  2860  :  (335, 128)
descriptor shape  2861  :  (215, 128)
descriptor shape  2862  :  (392, 128)
descriptor shape  2863  :  (398, 128)
descriptor shape  2864  :  (200, 128)
descriptor shape  2865  :  (259, 128)
descriptor shape  2866  :  (296, 128)
descriptor shape  2867  :  (274, 128)
descriptor shape  2868  :  (275, 128)
descriptor shape  2869  :  (326, 128)
descriptor shape  2870  :  (304, 128)
descriptor shape  2871  :  (285, 128)
descriptor shape  2872  :  (368, 128)
descriptor shape  2873  :  (254, 128)
descriptor shape  2874  :  (333, 128)
descriptor shape  2875  :  (258, 128)
descriptor shape  2876  :  (353, 128)
descriptor s

descriptor shape  3066  :  (208, 128)
descriptor shape  3067  :  (511, 128)
descriptor shape  3068  :  (254, 128)
descriptor shape  3069  :  (160, 128)
descriptor shape  3070  :  (343, 128)
descriptor shape  3071  :  (280, 128)
descriptor shape  3072  :  (325, 128)
descriptor shape  3073  :  (266, 128)
descriptor shape  3074  :  (118, 128)
descriptor shape  3075  :  (233, 128)
descriptor shape  3076  :  (180, 128)
descriptor shape  3077  :  (401, 128)
descriptor shape  3078  :  (233, 128)
descriptor shape  3079  :  (289, 128)
descriptor shape  3080  :  (240, 128)
descriptor shape  3081  :  (307, 128)
descriptor shape  3082  :  (337, 128)
descriptor shape  3083  :  (113, 128)
descriptor shape  3084  :  (247, 128)
descriptor shape  3085  :  (227, 128)
descriptor shape  3086  :  (495, 128)
descriptor shape  3087  :  (219, 128)
descriptor shape  3088  :  (364, 128)
descriptor shape  3089  :  (284, 128)
descriptor shape  3090  :  (331, 128)
descriptor shape  3091  :  (491, 128)
descriptor s

In [4]:
data1 = pd.read_csv(r'D:\CV_datasets\370x370\crowded.csv',header=None,dtype='float64')
#MemoryError: Unable to allocate 166. MiB for an array with shape (128, 169606) and data type float64,
#Double-precision floating-point format

data1=data1.astype(np.float64) 
#as unit8 contain 1 byte(8bit) and ranges from 0 to 255
data1

0     1     2      3      4     5     6     7      8      9    ...  \
0       96.0   8.0   3.0   41.0   10.0   0.0   0.0  15.0  156.0   26.0  ...   
1        0.0   0.0   0.0    5.0   48.0   7.0   0.0   0.0   68.0   16.0  ...   
2        2.0   3.0  18.0    5.0    0.0   3.0  14.0   3.0   15.0    5.0  ...   
3       73.0  94.0  12.0    0.0    2.0   4.0   0.0   0.0   34.0  132.0  ...   
4       42.0  12.0   1.0    4.0  169.0  11.0   1.0   2.0  169.0   37.0  ...   
...      ...   ...   ...    ...    ...   ...   ...   ...    ...    ...  ...   
884240  17.0   2.0   0.0    3.0  130.0  17.0   0.0   0.0  145.0    6.0  ...   
884241  31.0   1.0   0.0    0.0    6.0   5.0   2.0  17.0   45.0   11.0  ...   
884242  12.0   0.0   6.0   50.0   40.0  13.0  15.0  65.0   10.0   28.0  ...   
884243  34.0   2.0   0.0    9.0   50.0   4.0   3.0  16.0  126.0    5.0  ...   
884244  78.0  27.0  15.0  146.0  136.0   3.0   0.0   7.0  139.0    6.0  ...   

         118    119    120   121   122   123    124   125  126   127  
0        9.0   11.0    0.0   0.0   0.0   0.0    0.0   0.0  0.0   0.0  
1        1.0    2.0   15.0  17.0  10.0  26.0  142.0  20.0  0.0   0.0  
2        0.0    0.0    0.0   0.0   0.0   0.0    0.0   0.0  0.0   0.0  
3        7.0   68.0   69.0  11.0   0.0   0.0    0.0   0.0  0.0   4.0  
4       20.0   12.0    0.0   0.0   0.0   0.0    0.0   0.0  0.0   0.0  
...      ...    ...    ...   ...   ...   ...    ...   ...  ...   ...  
884240   1.0    3.0    4.0   6.0   4.0   2.0   50.0  53.0  1.0   1.0  
884241   1.0   32.0    9.0  17.0  12.0  19.0   69.0  22.0  1.0   1.0  
884242   1.0   86.0  126.0   1.0   1.0   4.0   19.0   2.0  0.0  90.0  
884243   0.0  122.0   48.0   0.0   0.0  43.0  117.0   0.0  1.0  56.0  
884244  12.0   22.0    0.0   0.0   0.0   0.0    0.0   0.0  0.0   0.0  

[884245 rows x 128 columns]

In [5]:
i=0
for filename in os.listdir(folder2):
    
    path=os.path.join(folder2,filename)
    a=cv2.imread(path)
    if a is None:
        continue
    
    #resize image
    resize=(100,300)
    img=cv2.resize(a,resize)
    resultimage = np.zeros((100, 300))
   
    #normalizing the given image using normalize() function
    nimg = cv2.normalize(img,resultimage, 0, 255, cv2.NORM_MINMAX)
    
    
    gray = cv2.cvtColor(nimg, cv2.COLOR_BGR2GRAY)
    hist_image=cv2.equalizeHist(gray)
    
    #initialise sift descriptor
    sift = cv2.xfeatures2d.SIFT_create()
    keypoints, descriptors = sift.detectAndCompute(hist_image, None)
    
    #convert the descriptor array into a dataframe format
    out=pd.DataFrame(descriptors)
    print("descriptor shape ",i," : ", out.shape)
    i=i+1
    #drop first coloumn as it's the no of feature detected. Not required.
    #append to the csv file
    csv_data=out.to_csv(r'D:\CV_datasets\370x370\Non-crowded.csv', mode='a', header=False,index=False)

descriptor shape  0  :  (218, 128)
descriptor shape  1  :  (124, 128)
descriptor shape  2  :  (153, 128)
descriptor shape  3  :  (139, 128)
descriptor shape  4  :  (284, 128)
descriptor shape  5  :  (350, 128)
descriptor shape  6  :  (296, 128)
descriptor shape  7  :  (114, 128)
descriptor shape  8  :  (260, 128)
descriptor shape  9  :  (325, 128)
descriptor shape  10  :  (284, 128)
descriptor shape  11  :  (108, 128)
descriptor shape  12  :  (197, 128)
descriptor shape  13  :  (222, 128)
descriptor shape  14  :  (385, 128)
descriptor shape  15  :  (131, 128)
descriptor shape  16  :  (257, 128)
descriptor shape  17  :  (118, 128)
descriptor shape  18  :  (189, 128)
descriptor shape  19  :  (108, 128)
descriptor shape  20  :  (624, 128)
descriptor shape  21  :  (120, 128)
descriptor shape  22  :  (591, 128)
descriptor shape  23  :  (138, 128)
descriptor shape  24  :  (407, 128)
descriptor shape  25  :  (339, 128)
descriptor shape  26  :  (366, 128)
descriptor shape  27  :  (189, 128)
de

descriptor shape  228  :  (248, 128)
descriptor shape  229  :  (81, 128)
descriptor shape  230  :  (276, 128)
descriptor shape  231  :  (241, 128)
descriptor shape  232  :  (236, 128)
descriptor shape  233  :  (518, 128)
descriptor shape  234  :  (359, 128)
descriptor shape  235  :  (393, 128)
descriptor shape  236  :  (126, 128)
descriptor shape  237  :  (264, 128)
descriptor shape  238  :  (319, 128)
descriptor shape  239  :  (114, 128)
descriptor shape  240  :  (178, 128)
descriptor shape  241  :  (97, 128)
descriptor shape  242  :  (267, 128)
descriptor shape  243  :  (79, 128)
descriptor shape  244  :  (209, 128)
descriptor shape  245  :  (321, 128)
descriptor shape  246  :  (256, 128)
descriptor shape  247  :  (143, 128)
descriptor shape  248  :  (74, 128)
descriptor shape  249  :  (337, 128)
descriptor shape  250  :  (278, 128)
descriptor shape  251  :  (144, 128)
descriptor shape  252  :  (241, 128)
descriptor shape  253  :  (245, 128)
descriptor shape  254  :  (142, 128)
descr

descriptor shape  455  :  (230, 128)
descriptor shape  456  :  (407, 128)
descriptor shape  457  :  (279, 128)
descriptor shape  458  :  (275, 128)
descriptor shape  459  :  (366, 128)
descriptor shape  460  :  (118, 128)
descriptor shape  461  :  (386, 128)
descriptor shape  462  :  (310, 128)
descriptor shape  463  :  (248, 128)
descriptor shape  464  :  (124, 128)
descriptor shape  465  :  (204, 128)
descriptor shape  466  :  (301, 128)
descriptor shape  467  :  (174, 128)
descriptor shape  468  :  (344, 128)
descriptor shape  469  :  (147, 128)
descriptor shape  470  :  (154, 128)
descriptor shape  471  :  (324, 128)
descriptor shape  472  :  (245, 128)
descriptor shape  473  :  (71, 128)
descriptor shape  474  :  (231, 128)
descriptor shape  475  :  (87, 128)
descriptor shape  476  :  (206, 128)
descriptor shape  477  :  (182, 128)
descriptor shape  478  :  (408, 128)
descriptor shape  479  :  (324, 128)
descriptor shape  480  :  (37, 128)
descriptor shape  481  :  (155, 128)
desc

descriptor shape  681  :  (242, 128)
descriptor shape  682  :  (67, 128)
descriptor shape  683  :  (408, 128)
descriptor shape  684  :  (488, 128)
descriptor shape  685  :  (54, 128)
descriptor shape  686  :  (496, 128)
descriptor shape  687  :  (340, 128)
descriptor shape  688  :  (200, 128)
descriptor shape  689  :  (49, 128)
descriptor shape  690  :  (127, 128)
descriptor shape  691  :  (142, 128)
descriptor shape  692  :  (394, 128)
descriptor shape  693  :  (422, 128)
descriptor shape  694  :  (194, 128)
descriptor shape  695  :  (336, 128)
descriptor shape  696  :  (196, 128)
descriptor shape  697  :  (327, 128)
descriptor shape  698  :  (397, 128)
descriptor shape  699  :  (379, 128)
descriptor shape  700  :  (324, 128)
descriptor shape  701  :  (8, 128)
descriptor shape  702  :  (296, 128)
descriptor shape  703  :  (315, 128)
descriptor shape  704  :  (216, 128)
descriptor shape  705  :  (115, 128)
descriptor shape  706  :  (173, 128)
descriptor shape  707  :  (197, 128)
descri

descriptor shape  907  :  (499, 128)
descriptor shape  908  :  (475, 128)
descriptor shape  909  :  (297, 128)
descriptor shape  910  :  (303, 128)
descriptor shape  911  :  (206, 128)
descriptor shape  912  :  (361, 128)
descriptor shape  913  :  (239, 128)
descriptor shape  914  :  (129, 128)
descriptor shape  915  :  (306, 128)
descriptor shape  916  :  (195, 128)
descriptor shape  917  :  (108, 128)
descriptor shape  918  :  (119, 128)
descriptor shape  919  :  (281, 128)
descriptor shape  920  :  (238, 128)
descriptor shape  921  :  (291, 128)
descriptor shape  922  :  (206, 128)
descriptor shape  923  :  (295, 128)
descriptor shape  924  :  (392, 128)
descriptor shape  925  :  (214, 128)
descriptor shape  926  :  (46, 128)
descriptor shape  927  :  (148, 128)
descriptor shape  928  :  (193, 128)
descriptor shape  929  :  (97, 128)
descriptor shape  930  :  (71, 128)
descriptor shape  931  :  (209, 128)
descriptor shape  932  :  (387, 128)
descriptor shape  933  :  (415, 128)
desc

descriptor shape  1130  :  (307, 128)
descriptor shape  1131  :  (407, 128)
descriptor shape  1132  :  (201, 128)
descriptor shape  1133  :  (297, 128)
descriptor shape  1134  :  (189, 128)
descriptor shape  1135  :  (425, 128)
descriptor shape  1136  :  (190, 128)
descriptor shape  1137  :  (236, 128)
descriptor shape  1138  :  (277, 128)
descriptor shape  1139  :  (142, 128)
descriptor shape  1140  :  (190, 128)
descriptor shape  1141  :  (125, 128)
descriptor shape  1142  :  (117, 128)
descriptor shape  1143  :  (454, 128)
descriptor shape  1144  :  (151, 128)
descriptor shape  1145  :  (187, 128)
descriptor shape  1146  :  (259, 128)
descriptor shape  1147  :  (296, 128)
descriptor shape  1148  :  (244, 128)
descriptor shape  1149  :  (56, 128)
descriptor shape  1150  :  (311, 128)
descriptor shape  1151  :  (378, 128)
descriptor shape  1152  :  (595, 128)
descriptor shape  1153  :  (284, 128)
descriptor shape  1154  :  (248, 128)
descriptor shape  1155  :  (143, 128)
descriptor sh

descriptor shape  1347  :  (119, 128)
descriptor shape  1348  :  (202, 128)
descriptor shape  1349  :  (82, 128)
descriptor shape  1350  :  (149, 128)
descriptor shape  1351  :  (106, 128)
descriptor shape  1352  :  (440, 128)
descriptor shape  1353  :  (93, 128)
descriptor shape  1354  :  (218, 128)
descriptor shape  1355  :  (452, 128)
descriptor shape  1356  :  (117, 128)
descriptor shape  1357  :  (321, 128)
descriptor shape  1358  :  (132, 128)
descriptor shape  1359  :  (249, 128)
descriptor shape  1360  :  (202, 128)
descriptor shape  1361  :  (253, 128)
descriptor shape  1362  :  (254, 128)
descriptor shape  1363  :  (225, 128)
descriptor shape  1364  :  (409, 128)
descriptor shape  1365  :  (202, 128)
descriptor shape  1366  :  (107, 128)
descriptor shape  1367  :  (289, 128)
descriptor shape  1368  :  (170, 128)
descriptor shape  1369  :  (344, 128)
descriptor shape  1370  :  (392, 128)
descriptor shape  1371  :  (430, 128)
descriptor shape  1372  :  (353, 128)
descriptor sha

descriptor shape  1566  :  (156, 128)
descriptor shape  1567  :  (253, 128)
descriptor shape  1568  :  (213, 128)
descriptor shape  1569  :  (414, 128)
descriptor shape  1570  :  (285, 128)
descriptor shape  1571  :  (187, 128)
descriptor shape  1572  :  (72, 128)
descriptor shape  1573  :  (387, 128)
descriptor shape  1574  :  (214, 128)
descriptor shape  1575  :  (139, 128)
descriptor shape  1576  :  (181, 128)
descriptor shape  1577  :  (415, 128)
descriptor shape  1578  :  (109, 128)
descriptor shape  1579  :  (267, 128)
descriptor shape  1580  :  (197, 128)
descriptor shape  1581  :  (378, 128)
descriptor shape  1582  :  (100, 128)
descriptor shape  1583  :  (142, 128)
descriptor shape  1584  :  (234, 128)
descriptor shape  1585  :  (399, 128)
descriptor shape  1586  :  (135, 128)
descriptor shape  1587  :  (275, 128)
descriptor shape  1588  :  (160, 128)
descriptor shape  1589  :  (205, 128)
descriptor shape  1590  :  (278, 128)
descriptor shape  1591  :  (50, 128)
descriptor sha

descriptor shape  1786  :  (174, 128)
descriptor shape  1787  :  (187, 128)
descriptor shape  1788  :  (261, 128)
descriptor shape  1789  :  (222, 128)
descriptor shape  1790  :  (278, 128)
descriptor shape  1791  :  (227, 128)
descriptor shape  1792  :  (349, 128)
descriptor shape  1793  :  (91, 128)
descriptor shape  1794  :  (210, 128)
descriptor shape  1795  :  (277, 128)
descriptor shape  1796  :  (121, 128)
descriptor shape  1797  :  (422, 128)
descriptor shape  1798  :  (215, 128)
descriptor shape  1799  :  (265, 128)
descriptor shape  1800  :  (488, 128)
descriptor shape  1801  :  (340, 128)
descriptor shape  1802  :  (166, 128)
descriptor shape  1803  :  (233, 128)
descriptor shape  1804  :  (376, 128)
descriptor shape  1805  :  (304, 128)
descriptor shape  1806  :  (299, 128)
descriptor shape  1807  :  (258, 128)
descriptor shape  1808  :  (306, 128)
descriptor shape  1809  :  (358, 128)
descriptor shape  1810  :  (184, 128)
descriptor shape  1811  :  (291, 128)
descriptor sh

descriptor shape  2005  :  (187, 128)
descriptor shape  2006  :  (285, 128)
descriptor shape  2007  :  (178, 128)
descriptor shape  2008  :  (222, 128)
descriptor shape  2009  :  (406, 128)
descriptor shape  2010  :  (270, 128)
descriptor shape  2011  :  (243, 128)
descriptor shape  2012  :  (168, 128)
descriptor shape  2013  :  (242, 128)
descriptor shape  2014  :  (136, 128)
descriptor shape  2015  :  (368, 128)
descriptor shape  2016  :  (220, 128)
descriptor shape  2017  :  (303, 128)
descriptor shape  2018  :  (216, 128)
descriptor shape  2019  :  (394, 128)
descriptor shape  2020  :  (237, 128)
descriptor shape  2021  :  (92, 128)
descriptor shape  2022  :  (252, 128)
descriptor shape  2023  :  (311, 128)
descriptor shape  2024  :  (227, 128)
descriptor shape  2025  :  (301, 128)
descriptor shape  2026  :  (118, 128)
descriptor shape  2027  :  (445, 128)
descriptor shape  2028  :  (535, 128)
descriptor shape  2029  :  (256, 128)
descriptor shape  2030  :  (303, 128)
descriptor sh

descriptor shape  2226  :  (135, 128)
descriptor shape  2227  :  (113, 128)
descriptor shape  2228  :  (252, 128)
descriptor shape  2229  :  (233, 128)
descriptor shape  2230  :  (329, 128)
descriptor shape  2231  :  (120, 128)
descriptor shape  2232  :  (178, 128)
descriptor shape  2233  :  (337, 128)
descriptor shape  2234  :  (123, 128)
descriptor shape  2235  :  (137, 128)
descriptor shape  2236  :  (183, 128)
descriptor shape  2237  :  (281, 128)
descriptor shape  2238  :  (59, 128)
descriptor shape  2239  :  (386, 128)
descriptor shape  2240  :  (299, 128)
descriptor shape  2241  :  (264, 128)
descriptor shape  2242  :  (379, 128)
descriptor shape  2243  :  (471, 128)
descriptor shape  2244  :  (323, 128)
descriptor shape  2245  :  (209, 128)
descriptor shape  2246  :  (69, 128)
descriptor shape  2247  :  (283, 128)
descriptor shape  2248  :  (212, 128)
descriptor shape  2249  :  (108, 128)
descriptor shape  2250  :  (320, 128)
descriptor shape  2251  :  (176, 128)
descriptor sha

descriptor shape  2446  :  (182, 128)
descriptor shape  2447  :  (179, 128)
descriptor shape  2448  :  (205, 128)
descriptor shape  2449  :  (233, 128)
descriptor shape  2450  :  (401, 128)
descriptor shape  2451  :  (213, 128)
descriptor shape  2452  :  (123, 128)
descriptor shape  2453  :  (247, 128)
descriptor shape  2454  :  (394, 128)
descriptor shape  2455  :  (135, 128)
descriptor shape  2456  :  (409, 128)
descriptor shape  2457  :  (115, 128)
descriptor shape  2458  :  (178, 128)
descriptor shape  2459  :  (297, 128)
descriptor shape  2460  :  (183, 128)
descriptor shape  2461  :  (361, 128)
descriptor shape  2462  :  (458, 128)
descriptor shape  2463  :  (272, 128)
descriptor shape  2464  :  (221, 128)
descriptor shape  2465  :  (271, 128)
descriptor shape  2466  :  (411, 128)
descriptor shape  2467  :  (297, 128)
descriptor shape  2468  :  (221, 128)
descriptor shape  2469  :  (301, 128)
descriptor shape  2470  :  (66, 128)
descriptor shape  2471  :  (169, 128)
descriptor sh

descriptor shape  2664  :  (365, 128)
descriptor shape  2665  :  (108, 128)
descriptor shape  2666  :  (282, 128)
descriptor shape  2667  :  (347, 128)
descriptor shape  2668  :  (210, 128)
descriptor shape  2669  :  (322, 128)
descriptor shape  2670  :  (54, 128)
descriptor shape  2671  :  (276, 128)
descriptor shape  2672  :  (262, 128)
descriptor shape  2673  :  (211, 128)
descriptor shape  2674  :  (198, 128)
descriptor shape  2675  :  (413, 128)
descriptor shape  2676  :  (48, 128)
descriptor shape  2677  :  (190, 128)
descriptor shape  2678  :  (343, 128)
descriptor shape  2679  :  (146, 128)
descriptor shape  2680  :  (396, 128)
descriptor shape  2681  :  (116, 128)
descriptor shape  2682  :  (117, 128)
descriptor shape  2683  :  (82, 128)
descriptor shape  2684  :  (198, 128)
descriptor shape  2685  :  (120, 128)
descriptor shape  2686  :  (504, 128)
descriptor shape  2687  :  (211, 128)
descriptor shape  2688  :  (469, 128)
descriptor shape  2689  :  (220, 128)
descriptor shap

descriptor shape  2885  :  (354, 128)
descriptor shape  2886  :  (258, 128)
descriptor shape  2887  :  (597, 128)
descriptor shape  2888  :  (257, 128)
descriptor shape  2889  :  (290, 128)
descriptor shape  2890  :  (361, 128)
descriptor shape  2891  :  (151, 128)
descriptor shape  2892  :  (339, 128)
descriptor shape  2893  :  (197, 128)
descriptor shape  2894  :  (126, 128)
descriptor shape  2895  :  (322, 128)
descriptor shape  2896  :  (209, 128)
descriptor shape  2897  :  (417, 128)
descriptor shape  2898  :  (388, 128)
descriptor shape  2899  :  (336, 128)
descriptor shape  2900  :  (220, 128)
descriptor shape  2901  :  (193, 128)
descriptor shape  2902  :  (167, 128)
descriptor shape  2903  :  (147, 128)
descriptor shape  2904  :  (155, 128)
descriptor shape  2905  :  (75, 128)
descriptor shape  2906  :  (335, 128)
descriptor shape  2907  :  (146, 128)
descriptor shape  2908  :  (195, 128)
descriptor shape  2909  :  (450, 128)
descriptor shape  2910  :  (154, 128)
descriptor sh

In [6]:
data2= pd.read_csv(r'D:\CV_datasets\370x370\Non-crowded.csv',header=None,dtype='float64')
data2=data2.astype(np.float64)
data2

0     1     2     3     4     5     6     7      8     9    ...  \
0        3.0   7.0  10.0  41.0  61.0  22.0   5.0   1.0   11.0  12.0  ...   
1        1.0   6.0  93.0  45.0  18.0  63.0  26.0  19.0   33.0  32.0  ...   
2        0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   79.0  31.0  ...   
3        1.0   6.0   5.0   0.0   0.0   1.0   1.0   0.0   29.0  71.0  ...   
4        1.0   3.0   5.0   7.0   2.0   6.0   6.0   1.0   35.0  13.0  ...   
...      ...   ...   ...   ...   ...   ...   ...   ...    ...   ...  ...   
745834   2.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   11.0   1.0  ...   
745835   0.0   1.0   0.0   0.0   0.0   0.0   0.0   0.0   12.0  48.0  ...   
745836   1.0   0.0   0.0   0.0   1.0   1.0   1.0   2.0    2.0   2.0  ...   
745837   2.0   1.0  23.0  32.0  54.0  95.0  66.0  20.0   12.0  34.0  ...   
745838  54.0  36.0  12.0  33.0  88.0  55.0   2.0   1.0  107.0  75.0  ...   

         118   119   120   121    122   123   124   125   126    127  
0        0.0   4.0   1.0   4.0    5.0  16.0   7.0   0.0   0.0    0.0  
1       19.0   1.0   0.0   1.0    0.0   0.0   0.0   0.0   0.0    0.0  
2        9.0  31.0  27.0   9.0    5.0  42.0  33.0   4.0  40.0  116.0  
3        1.0   3.0   3.0  40.0   84.0  56.0  13.0   3.0   2.0    2.0  
4       46.0   7.0   8.0  11.0  109.0  96.0   4.0  27.0  24.0    4.0  
...      ...   ...   ...   ...    ...   ...   ...   ...   ...    ...  
745834  40.0  23.0  41.0  15.0    2.0   1.0   4.0  18.0  31.0   21.0  
745835   4.0  39.0   6.0   3.0    4.0  15.0  55.0  57.0  26.0    9.0  
745836  33.0  27.0  54.0  98.0   67.0  19.0   2.0   1.0  22.0   32.0  
745837   5.0   0.0   1.0   2.0    1.0   2.0   1.0   0.0   0.0    0.0  
745838  16.0  27.0   1.0   1.0    0.0   0.0   0.0   0.0   1.0    1.0  

[745839 rows x 128 columns]

In [7]:
data=data1.append(data2)

In [8]:
csv_data=data.to_csv(r'D:\CV_datasets\370x370\Sift-final.csv', mode='a', header=False,index=False)

In [9]:
data= pd.read_csv(r'D:\CV_datasets\370x370\Sift-final.csv',header=None,dtype='float64')
data=data.astype(np.float64)
data

0     1     2     3      4     5     6     7      8      9    ...  \
0        96.0   8.0   3.0  41.0   10.0   0.0   0.0  15.0  156.0   26.0  ...   
1         0.0   0.0   0.0   5.0   48.0   7.0   0.0   0.0   68.0   16.0  ...   
2         2.0   3.0  18.0   5.0    0.0   3.0  14.0   3.0   15.0    5.0  ...   
3        73.0  94.0  12.0   0.0    2.0   4.0   0.0   0.0   34.0  132.0  ...   
4        42.0  12.0   1.0   4.0  169.0  11.0   1.0   2.0  169.0   37.0  ...   
...       ...   ...   ...   ...    ...   ...   ...   ...    ...    ...  ...   
1630079   2.0   0.0   0.0   0.0    0.0   0.0   0.0   0.0   11.0    1.0  ...   
1630080   0.0   1.0   0.0   0.0    0.0   0.0   0.0   0.0   12.0   48.0  ...   
1630081   1.0   0.0   0.0   0.0    1.0   1.0   1.0   2.0    2.0    2.0  ...   
1630082   2.0   1.0  23.0  32.0   54.0  95.0  66.0  20.0   12.0   34.0  ...   
1630083  54.0  36.0  12.0  33.0   88.0  55.0   2.0   1.0  107.0   75.0  ...   

          118   119   120   121   122   123    124   125   126   127  
0         9.0  11.0   0.0   0.0   0.0   0.0    0.0   0.0   0.0   0.0  
1         1.0   2.0  15.0  17.0  10.0  26.0  142.0  20.0   0.0   0.0  
2         0.0   0.0   0.0   0.0   0.0   0.0    0.0   0.0   0.0   0.0  
3         7.0  68.0  69.0  11.0   0.0   0.0    0.0   0.0   0.0   4.0  
4        20.0  12.0   0.0   0.0   0.0   0.0    0.0   0.0   0.0   0.0  
...       ...   ...   ...   ...   ...   ...    ...   ...   ...   ...  
1630079  40.0  23.0  41.0  15.0   2.0   1.0    4.0  18.0  31.0  21.0  
1630080   4.0  39.0   6.0   3.0   4.0  15.0   55.0  57.0  26.0   9.0  
1630081  33.0  27.0  54.0  98.0  67.0  19.0    2.0   1.0  22.0  32.0  
1630082   5.0   0.0   1.0   2.0   1.0   2.0    1.0   0.0   0.0   0.0  
1630083  16.0  27.0   1.0   1.0   0.0   0.0    0.0   0.0   1.0   1.0  

[1630084 rows x 128 columns]

# Kmeans

In [10]:
# # Find K value in Kmeans :- we will used elbow method

# SSE = []

# for k in range(1,16):
#     KM_Model = KMeans(n_clusters = k )
#     KM_Model.fit(data)
#     SSE.append(KM_Model.inertia_)
#     print(k)
    
# SSE

In [11]:
# # Plot between Acc and K value.
# # X_Axis = K value
# # Y_Axis = SSE
# import matplotlib.pyplot as plt
# plt.plot(range(1,16),SSE,'*-')
# plt.xlabel("K_Value")
# plt.ylabel("Acc")

In [12]:
kmeans = KMeans(n_clusters=5)
kmeans.fit(data)

KMeans(n_clusters=5)

In [13]:
import pickle

In [14]:
# save the model to disk
filename = r'D:\CV_datasets\370x370\Kmeans_CL_5_Model.sav'
pickle.dump(kmeans, open(filename, 'wb'))

In [15]:
hist=np.histogram(kmeans.labels_,bins=[0,1,2,3,4,5])


print('histogram of trained kmeans')
print(hist,"\n")

histogram of trained kmeans
(array([328995, 324177, 334497, 327926, 314489], dtype=int64), array([0, 1, 2, 3, 4, 5])) 



In [20]:
from sklearn.preprocessing import Normalizer

In [22]:
#performing kmeans prediction of the entire Crowded dataset with the pretrained kmeans model

#initialising i=0; as its the first class
i=0
data=[]
#k=0

for filename in os.listdir(folder1):
    #path
    path=os.path.join(folder1,filename)
    a=cv2.imread(path)
    if a is None:
        continue

    #resize image
    resize=(100,300)
    img=cv2.resize(a,resize)
    
    resultimage = np.zeros((100, 300))
   
    #normalizing the given image using normalize() function
    nimg = cv2.normalize(img,resultimage, 0, 255, cv2.NORM_MINMAX)
    
    
    #gray image
    gray = cv2.cvtColor(nimg, cv2.COLOR_BGR2GRAY)
    hist_image=cv2.equalizeHist(gray)
 
    
    sift = cv2.xfeatures2d.SIFT_create()
    keypoints, descriptors = sift.detectAndCompute(hist_image, None)
    
    out=pd.DataFrame(descriptors)
    
    
    #predict values of feature vector with pretrained kmeans
    #ValueError: Buffer dtype mismatch, expected 'float', in order to avoid this dtype=np.double
    
    array_double = np.array(out, dtype=np.double)
    if (array_double.any() == 0):
        continue
    a=kmeans.predict(array_double)
    
    hist=np.histogram(a,bins=[0,1,2,3,4,5])
    
    #append the dataframe into the array in append mode, the array will only have 5 values which will store the values in a row
    data.append(hist[0])
    
    #Normalization
    norm = Normalizer()
    normalized = norm.fit_transform(data)
    #k=k+1
    


#convert Array to Dataframe and append to the list
Output = pd.DataFrame(normalized)

#add row class 
Output["Class"] = i 
csv_data=Output.to_csv(r'D:\CV_datasets\370x370\final-crowded.csv', mode='a',header=False,index=False)  #D:\StrData\FinalStr.csv

In [23]:
#performing kmeans prediction of the entire Non_Crowded dataset with the pretrained kmeans model

#initialising i=1; as its the 2nd class
i=1
data=[]
k=0
for filename in os.listdir(folder2):
    path=os.path.join(folder2,filename)
    a=cv2.imread(path)
    if a is None:
        continue
    resize=(100,300)
    img=cv2.resize(a,resize)
    
    resultimage = np.zeros((100, 300))
   
    #normalizing the given image using normalize() function
    nimg = cv2.normalize(img,resultimage, 0, 255, cv2.NORM_MINMAX)
    
    
    gray = cv2.cvtColor(nimg, cv2.COLOR_BGR2GRAY)
    hist_image=cv2.equalizeHist(gray)
    
    sift = cv2.xfeatures2d.SIFT_create()
    keypoints, descriptors = sift.detectAndCompute(hist_image, None)
     
    out=pd.DataFrame(descriptors)
    
    #predict values of feature vector with pretrained kmeans
    #ValueError: Buffer dtype mismatch, expected 'float' but got 'double', in order to avoid this dtype=np.double
    
    array_double = np.array(out, dtype=np.double)
    if (array_double.any() == 0):
        continue
    a=kmeans.predict(array_double)
    hist=np.histogram(a,bins=[0,1,2,3,4,5])
    #append the dataframe into the array in append mode, the array will only have 5 values which will store the values in a row
    data.append(hist[0])
    
    #Normalization
    norm = Normalizer()
    normalized = norm.fit_transform(data)
    k=k+1
    

#convert Array to Dataframe and append to the list
Output = pd.DataFrame(normalized)

#add row class 
Output["Class"] = i 
csv_data=Output.to_csv(r'D:\CV_datasets\370x370\final-Non-crowded.csv', mode='a',header=False,index=False)

In [24]:
#Displaying the kmeans predicted data
print("Crowded")
dat1= pd.read_csv(r'D:\CV_datasets\370x370\final-crowded.csv',header=None)   ##D:\StrData\FinalStr.csv
print(dat1)

Crowded
             0         1         2         3         4  5
0     0.224267  0.217033  0.680036  0.585988  0.311080  0
1     0.270345  0.329116  0.540690  0.552444  0.470165  0
2     0.163601  0.157057  0.700214  0.588965  0.333747  0
3     0.430406  0.418282  0.563771  0.454654  0.339475  0
4     0.409787  0.510968  0.521087  0.455318  0.303546  0
...        ...       ...       ...       ...       ... ..
3103  0.331521  0.514429  0.411543  0.560155  0.377248  0
3104  0.391533  0.382634  0.444924  0.551705  0.444924  0
3105  0.215455  0.205196  0.523249  0.543769  0.584808  0
3106  0.569429  0.625746  0.350418  0.319130  0.244041  0
3107  0.252663  0.180473  0.640680  0.631657  0.306805  0

[3108 rows x 6 columns]


In [25]:
print("Non-Crowded")
dat2= pd.read_csv(r'D:\CV_datasets\370x370\final-Non-crowded.csv',header=None)       #D:/StrData/FinalNstr.csv
print(dat2)

Non-Crowded
             0         1         2         3         4  5
0     0.556059  0.708527  0.188343  0.134531  0.367717  1
1     0.592965  0.592965  0.406604  0.288012  0.220244  1
2     0.318067  0.318067  0.373383  0.401041  0.705279  1
3     0.540819  0.555051  0.170785  0.113857  0.597747  1
4     0.556035  0.665778  0.329231  0.248752  0.278017  1
...        ...       ...       ...       ...       ... ..
2996  0.267205  0.246651  0.369976  0.390530  0.760506  1
2997  0.224116  0.263092  0.467720  0.555417  0.594394  1
2998  0.499526  0.493039  0.220570  0.233545  0.635761  1
2999  0.532476  0.833441  0.097235  0.078714  0.078714  1
3000  0.531619  0.564435  0.420045  0.269091  0.387229  1

[3001 rows x 6 columns]


In [26]:
#appending All classes into 1 csv file

A=dat1.append(dat2)

csv_data=A.to_csv(r'D:\CV_datasets\370x370\final-FV.csv', mode='a',header=False,index=False)

In [27]:
A

0         1         2         3         4  5
0     0.224267  0.217033  0.680036  0.585988  0.311080  0
1     0.270345  0.329116  0.540690  0.552444  0.470165  0
2     0.163601  0.157057  0.700214  0.588965  0.333747  0
3     0.430406  0.418282  0.563771  0.454654  0.339475  0
4     0.409787  0.510968  0.521087  0.455318  0.303546  0
...        ...       ...       ...       ...       ... ..
2996  0.267205  0.246651  0.369976  0.390530  0.760506  1
2997  0.224116  0.263092  0.467720  0.555417  0.594394  1
2998  0.499526  0.493039  0.220570  0.233545  0.635761  1
2999  0.532476  0.833441  0.097235  0.078714  0.078714  1
3000  0.531619  0.564435  0.420045  0.269091  0.387229  1

[6109 rows x 6 columns]

In [28]:
x = A.iloc[:,0:5].values

In [29]:
x

array([[0.22426704, 0.21703261, 0.68003553, 0.58598806, 0.31108008],
       [0.27034513, 0.32911581, 0.54069026, 0.55244439, 0.47016544],
       [0.16360149, 0.15705743, 0.7002144 , 0.58896538, 0.33374705],
       ...,
       [0.49952631, 0.49303896, 0.22057006, 0.23354477, 0.63576076],
       [0.53247589, 0.83344052, 0.09723473, 0.07871383, 0.07871383],
       [0.53161922, 0.56443522, 0.42004482, 0.26909121, 0.38722882]])

In [30]:
y = A.iloc[:,5].values

In [31]:
y

array([0, 0, 0, ..., 1, 1, 1], dtype=int64)

In [32]:
# #Normalization
# from sklearn.preprocessing import Normalizer
# norm = Normalizer().fit(x)
# normalized = norm.fit_transform(x)
# normalized

In [33]:
from sklearn.preprocessing import StandardScaler
DhoniS = StandardScaler()
Dhoni = DhoniS.fit_transform(x)

In [34]:
Dhoni

array([[-1.03883798, -1.05554514,  1.54735717,  1.01635612, -0.78086942],
       [-0.75923332, -0.38111303,  0.70875171,  0.81847744,  0.14146852],
       [-1.40696017, -1.41643053,  1.66879732,  1.03391973, -0.64945189],
       ...,
       [ 0.631452  ,  0.60525283, -1.21779049, -1.06275486,  1.10154963],
       [ 0.83139204,  2.65353268, -1.96004519, -1.97612367, -2.12807204],
       [ 0.82619373,  1.03486171, -0.01731472, -0.85306156, -0.33937771]])

In [35]:
from sklearn.decomposition import PCA

In [36]:
pca = PCA(n_components=None)
pca.fit(Dhoni)

PCA()

In [37]:
Bhumi = pca.transform(Dhoni)

In [38]:
Bhumi

array([[-2.26215941e+00, -9.35493153e-01,  3.15296628e-01,
         1.87779534e-01,  3.21286746e-01],
       [-1.33474848e+00, -7.80388347e-02,  1.10423917e-01,
        -2.59773853e-01, -2.15894797e-01],
       [-2.70994239e+00, -6.90402621e-01,  3.71115683e-01,
         2.23893841e-01,  5.03165801e-01],
       ...,
       [ 1.66534006e+00,  1.32080185e+00, -1.24026399e-01,
        -2.02042210e-03, -2.40154327e-01],
       [ 3.85445217e+00, -1.32362868e+00,  7.37232768e-01,
        -1.10237815e+00,  1.28079537e+00],
       [ 1.39813301e+00, -4.60977088e-01,  5.69742205e-01,
         2.34884249e-01, -2.22875114e-01]])

In [39]:
Bhumi = pd.DataFrame(Bhumi)

In [40]:
Bhumi

0         1         2         3         4
0    -2.262159 -0.935493  0.315297  0.187780  0.321287
1    -1.334748 -0.078039  0.110424 -0.259774 -0.215895
2    -2.709942 -0.690403  0.371116  0.223894  0.503166
3    -0.301193 -0.944984  0.345229  0.271661 -0.221497
4     0.059833 -1.128837  0.482839 -0.230991 -0.202380
...        ...       ...       ...       ...       ...
6104 -0.749080  2.051883 -0.170597  0.033047 -0.154828
6105 -1.525552  0.813488 -0.213445 -0.365376 -0.181707
6106  1.665340  1.320802 -0.124026 -0.002020 -0.240154
6107  3.854452 -1.323629  0.737233 -1.102378  1.280795
6108  1.398133 -0.460977  0.569742  0.234884 -0.222875

[6109 rows x 5 columns]

In [41]:
Bhumi.shape

(6109, 5)

In [42]:
print(pca.explained_variance_ratio_) 

[0.59889532 0.28221793 0.05317552 0.0438355  0.02187573]


In [43]:
pca = PCA(n_components=3)
pca.fit(Dhoni)

PCA(n_components=3)

In [44]:
# save the model to disk
filename = r'D:\CV_datasets\370x370\PCA_3_Model.sav'
pickle.dump(kmeans, open(filename, 'wb'))

In [45]:
Bhumi = pca.transform(Dhoni)

In [46]:
Bhumi

array([[-2.26215941, -0.93549315,  0.31529663],
       [-1.33474848, -0.07803883,  0.11042392],
       [-2.70994239, -0.69040262,  0.37111568],
       ...,
       [ 1.66534006,  1.32080185, -0.1240264 ],
       [ 3.85445217, -1.32362868,  0.73723277],
       [ 1.39813301, -0.46097709,  0.5697422 ]])

In [47]:
Bhumi.shape

(6109, 3)

In [48]:
print(pca.explained_variance_ratio_) 

[0.59889532 0.28221793 0.05317552]


In [49]:
Bhumi = pd.DataFrame(Bhumi)

In [50]:
Bhumi

0         1         2
0    -2.262159 -0.935493  0.315297
1    -1.334748 -0.078039  0.110424
2    -2.709942 -0.690403  0.371116
3    -0.301193 -0.944984  0.345229
4     0.059833 -1.128837  0.482839
...        ...       ...       ...
6104 -0.749080  2.051883 -0.170597
6105 -1.525552  0.813488 -0.213445
6106  1.665340  1.320802 -0.124026
6107  3.854452 -1.323629  0.737233
6108  1.398133 -0.460977  0.569742

[6109 rows x 3 columns]

In [51]:
B=pd.concat([Bhumi, pd.DataFrame(y)],axis=1)

In [52]:
B

0         1         2  0
0    -2.262159 -0.935493  0.315297  0
1    -1.334748 -0.078039  0.110424  0
2    -2.709942 -0.690403  0.371116  0
3    -0.301193 -0.944984  0.345229  0
4     0.059833 -1.128837  0.482839  0
...        ...       ...       ... ..
6104 -0.749080  2.051883 -0.170597  1
6105 -1.525552  0.813488 -0.213445  1
6106  1.665340  1.320802 -0.124026  1
6107  3.854452 -1.323629  0.737233  1
6108  1.398133 -0.460977  0.569742  1

[6109 rows x 4 columns]

In [53]:
csv_data=B.to_csv(r'D:\CV_datasets\370x370\final-PCA-FV.csv', mode='a',header=False,index=False)

# Training ,Testing & Classification

In [54]:
data= pd.read_csv(r'D:\CV_datasets\370x370\final-PCA-FV.csv',header=None) ##D:/StrData/FinalPCAFV.csv

data

0         1         2  3
0    -2.262159 -0.935493  0.315297  0
1    -1.334748 -0.078039  0.110424  0
2    -2.709942 -0.690403  0.371116  0
3    -0.301193 -0.944984  0.345229  0
4     0.059833 -1.128837  0.482839  0
...        ...       ...       ... ..
6104 -0.749080  2.051883 -0.170597  1
6105 -1.525552  0.813488 -0.213445  1
6106  1.665340  1.320802 -0.124026  1
6107  3.854452 -1.323629  0.737233  1
6108  1.398133 -0.460977  0.569742  1

[6109 rows x 4 columns]

In [55]:
#assigning x the columns from 1 to 128 for training
x = data.iloc[:,0:3].values
print("X values")
print(x)

#assigning y with the column "Class" as target variable
y = data.iloc[:,3]
print("Y values")
print(y)

X values
[[-2.26215941 -0.93549315  0.31529663]
 [-1.33474848 -0.07803883  0.11042392]
 [-2.70994239 -0.69040262  0.37111568]
 ...
 [ 1.66534006  1.32080185 -0.1240264 ]
 [ 3.85445217 -1.32362868  0.73723277]
 [ 1.39813301 -0.46097709  0.5697422 ]]
Y values
0       0
1       0
2       0
3       0
4       0
       ..
6104    1
6105    1
6106    1
6107    1
6108    1
Name: 3, Length: 6109, dtype: int64


In [56]:
#Dataset split into train and test with 80% Training and 20% Testing
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=.20, random_state=0)

# Decision Tree Classifier

In [57]:
#Decision Tree Classifier
from sklearn.metrics import accuracy_score
#Assign model with Decision Tree classifier
model1 = DecisionTreeClassifier(max_depth=13)
filename = r'D:\CV_datasets\370x370\model1.sav'
pickle.dump(kmeans, open(filename, 'wb'))
#training the model with the Training Variables 
model1.fit(x_train, y_train)
#predicting the target variable using testing variables
y_pred1 = model1.predict(x_test)
#Results


In [58]:
recall_sensitivity = metrics.recall_score(y_test,y_pred1, pos_label=1)
recall_specificity= metrics.recall_score(y_test, y_pred1, pos_label=0)
# print ("Confusion Matrix : \n", cm)
print("Testing Accuracy ",accuracy_score(y_test,y_pred1)*100)
print("Training Accuracy ",accuracy_score(y_train,model1.predict(x_train))*100)
print("Precision Score:",metrics.precision_score(y_test, y_pred1))
print("Recall Score:",metrics.recall_score(y_test, y_pred1))
print("F1 Score:",metrics.f1_score(y_test, y_pred1))
print("Sensitivity:",recall_sensitivity)
print("Specificity:",recall_specificity)

Testing Accuracy  78.23240589198036
Training Accuracy  92.5925925925926
Precision Score: 0.771004942339374
Recall Score: 0.7865546218487395
F1 Score: 0.778702163061564
Sensitivity: 0.7865546218487395
Specificity: 0.7783094098883573


In [59]:
#Recognition &Validation
#Assigning path with any any class image
data=[]
path=r"C:\Users\ADMIN\TY_ET_A3__63_65_77_Crowd_detection(before_resizing)\crowd-detection_dataset\104.jpg"


#Repeated the process of image pre-processing and feature extraction
a=cv2.imread(path)
#print(a.shape)
if a is None:
    print("X")


#resize image
resize=(120,350)
img=cv2.resize(a,resize)
resultimage = np.zeros((100, 300))
#normalizing the given image using normalize() function
nimg = cv2.normalize(img,resultimage,0, 255, cv2.NORM_MINMAX)
    
gray = cv2.cvtColor(nimg, cv2.COLOR_BGR2GRAY)
hist_image=cv2.equalizeHist(gray)

#initialise sift descriptor
sift = cv2.xfeatures2d.SIFT_create()
keypoints, descriptors = sift.detectAndCompute(hist_image, None)

#normalizing sift features 
#norm = Normalizer()
#normalized = norm.fit_transform(descriptors)


#convert the descriptor array into a dataframe format
out=pd.DataFrame(descriptors)
print("Descriptor Shape:",out.shape)

#initialise Kmeans and create 5 clusters


#train the model for the features i.e. for all elements in the Dataframe
array_double = np.array(out, dtype=np.double)
a=kmeans.predict(array_double)

#get the values of the histogram for one image only for 5 clusters i.e. in 5 bins
#kmeans.labels_ give us the label vlaue of the feature that its clustered into
#hist will give the histogram for all those vlaues
hist=np.histogram(a,bins=[0,1,2,3,4,5])

#append the dataframe into the array in append mode, the array will only have 5 values which will store the values in a row
data.append(hist[0])

Output = pd.DataFrame(data)
print("Histogram:\n",Output)

Descriptor Shape: (119, 128)
Histogram:
     0   1   2  3   4
0  38  26  12  8  35


In [60]:
from sklearn.preprocessing import StandardScaler
MuktaS = StandardScaler()
Mukta = MuktaS.fit_transform(Output)

In [61]:
Mukta

array([[0., 0., 0., 0., 0.]])

In [62]:
Mukta.shape

(1, 5)

In [63]:
MB = pca.transform(Mukta)

In [64]:
MB.shape

(1, 3)

In [65]:
MB

array([[-2.35406846e-16,  1.99335063e-16, -6.34378533e-17]])

In [66]:
#prediction
y_preddt = model1.predict(MB)

#prints the prediction of the class
print(y_preddt)

[1]


# SVM

In [67]:
from sklearn.svm import SVC
DhoniSVM_LK = SVC(kernel='rbf')
model5 = DhoniSVM_LK.fit(x_train, y_train)

In [68]:
filename = r'D:\CV_datasets\370x370\SVC_RBF_PCA_3.sav'
pickle.dump(model5, open(filename, 'wb'))

In [69]:
model5

SVC()

In [70]:
y_pred5 = model5.predict(x_test)
y_pred5

array([0, 0, 1, ..., 0, 0, 0], dtype=int64)

In [71]:
from sklearn.metrics import confusion_matrix
cm1=confusion_matrix(y_test, y_pred5)
cm1

array([[526, 101],
       [104, 491]], dtype=int64)

In [72]:
from sklearn.metrics import accuracy_score
recall_sensitivity = metrics.recall_score(y_test,y_pred5, pos_label=1)
recall_specificity= metrics.recall_score(y_test, y_pred5, pos_label=0)
# print ("Confusion Matrix : \n", cm)
print("Testing Accuracy ",accuracy_score(y_test,y_pred5)*100)
print("Training Accuracy ",accuracy_score(y_train,model5.predict(x_train))*100)
print("Precision Score:",metrics.precision_score(y_test, y_pred5))
print("Recall Score:",metrics.recall_score(y_test, y_pred5))
print("F1 Score:",metrics.f1_score(y_test, y_pred5))
print("Sensitivity:",recall_sensitivity)
print("Specificity:",recall_specificity)

Testing Accuracy  83.22422258592471
Training Accuracy  80.06957233476571
Precision Score: 0.8293918918918919
Recall Score: 0.8252100840336134
F1 Score: 0.8272957034540859
Sensitivity: 0.8252100840336134
Specificity: 0.8389154704944178


In [73]:
#y_pred1 = model1.predict(MB) 
y_predsvm =model5.predict(MB) 

#prints the prediction of the class
print(y_predsvm)

[0]


In [74]:
model6 = SVC(kernel='linear')
model6.fit(x_train, y_train)

SVC(kernel='linear')

In [75]:
y_pred6 = model6.predict(x_test)

In [76]:
from sklearn.metrics import accuracy_score
recall_sensitivity = metrics.recall_score(y_test,y_pred6, pos_label=1)
recall_specificity= metrics.recall_score(y_test, y_pred6, pos_label=0)
# print ("Confusion Matrix : \n", cm)
print("Testing Accuracy ",accuracy_score(y_test,y_pred6)*100)
print("Training Accuracy ",accuracy_score(y_train,model6.predict(x_train))*100)
print("Precision Score:",metrics.precision_score(y_test, y_pred6))
print("Recall Score:",metrics.recall_score(y_test, y_pred6))
print("F1 Score:",metrics.f1_score(y_test, y_pred6))
print("Sensitivity:",recall_sensitivity)
print("Specificity:",recall_specificity)

Testing Accuracy  82.3240589198036
Training Accuracy  79.86494782074892
Precision Score: 0.8163606010016694
Recall Score: 0.8218487394957983
F1 Score: 0.8190954773869347
Sensitivity: 0.8218487394957983
Specificity: 0.8245614035087719


In [77]:
model7 = SVC(kernel='poly')
model7.fit(x_train, y_train)

SVC(kernel='poly')

In [78]:
y_pred7 = model7.predict(x_test)

In [79]:
from sklearn.metrics import accuracy_score
recall_sensitivity = metrics.recall_score(y_test,y_pred7, pos_label=1)
recall_specificity= metrics.recall_score(y_test, y_pred7, pos_label=0)
# print ("Confusion Matrix : \n", cm)
print("Testing Accuracy ",accuracy_score(y_test,y_pred7)*100)
print("Training Accuracy ",accuracy_score(y_train,model7.predict(x_train))*100)
print("Precision Score:",metrics.precision_score(y_test, y_pred7))
print("Recall Score:",metrics.recall_score(y_test, y_pred7))
print("F1 Score:",metrics.f1_score(y_test, y_pred7))
print("Sensitivity:",recall_sensitivity)
print("Specificity:",recall_specificity)

Testing Accuracy  79.86906710310966
Training Accuracy  77.98240229179456
Precision Score: 0.8483033932135728
Recall Score: 0.7142857142857143
F1 Score: 0.7755474452554744
Sensitivity: 0.7142857142857143
Specificity: 0.8787878787878788


# Random Forest

In [80]:
#Random Forest CLassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
#Assign model with Decision Tree classifier
model4 = RandomForestClassifier(n_estimators=100, criterion='entropy', max_depth=None, min_samples_split=2,
                                min_samples_leaf=1, min_weight_fraction_leaf=0.0, max_features='log2',
                                max_leaf_nodes=None, min_impurity_decrease=0.0, bootstrap=True, oob_score=False, 
                                n_jobs=None, random_state=2, verbose=0, warm_start=False, class_weight=None, 
                                ccp_alpha=0.0, max_samples=None)
filename = r'D:\CV_datasets\370x370\model4.sav'
pickle.dump(kmeans, open(filename, 'wb'))
#training the model with the Training Variables 
model4.fit(x_train, y_train)
#predicting the traget variable using testing variables
y_pred4 = model4.predict(x_test)
#Results
#print(y_pred4)

In [81]:
recall_sensitivity = metrics.recall_score(y_test,y_pred4, pos_label=1)
recall_specificity= metrics.recall_score(y_test, y_pred4, pos_label=0)
# print ("Confusion Matrix : \n", cm)
print("Testing Accuracy ",accuracy_score(y_test,y_pred4)*100)
print("Training Accuracy ",accuracy_score(y_train,model4.predict(x_train))*100)
print("Precision Score:",metrics.precision_score(y_test, y_pred4))
print("Recall Score:",metrics.recall_score(y_test, y_pred4))
print("F1 Score:",metrics.f1_score(y_test, y_pred4))
print("Sensitivity:",recall_sensitivity)
print("Specificity:",recall_specificity)

Testing Accuracy  81.66939443535188
Training Accuracy  99.87722529158994
Precision Score: 0.8128161888701517
Recall Score: 0.8100840336134454
F1 Score: 0.8114478114478114
Sensitivity: 0.8100840336134454
Specificity: 0.8229665071770335


In [82]:
y_predRF = model4.predict(MB)

#prints the prediction of the class
print(y_predRF)

[1]


# KNN

In [83]:
from sklearn.neighbors import KNeighborsClassifier
model2 = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p = 2)
model2.fit(x_train, y_train)

KNeighborsClassifier()

In [84]:
y_pred2 = model2.predict(x_test)

In [85]:
recall_sensitivity = metrics.recall_score(y_test,y_pred2, pos_label=1)
recall_specificity= metrics.recall_score(y_test, y_pred2, pos_label=0)
# print ("Confusion Matrix : \n", cm)
print("Testing Accuracy ",accuracy_score(y_test,y_pred2)*100)
print("Training Accuracy ",accuracy_score(y_train,model2.predict(x_train))*100)
print("Precision Score:",metrics.precision_score(y_test, y_pred2))
print("Recall Score:",metrics.recall_score(y_test, y_pred2))
print("F1 Score:",metrics.f1_score(y_test, y_pred2))
print("Sensitivity:",recall_sensitivity)
print("Specificity:",recall_specificity)

Testing Accuracy  80.9328968903437
Training Accuracy  83.52772662164928
Precision Score: 0.8006644518272426
Recall Score: 0.8100840336134454
F1 Score: 0.8053467000835421
Sensitivity: 0.8100840336134454
Specificity: 0.8086124401913876


In [86]:
from sklearn.metrics import confusion_matrix,accuracy_score
cm = confusion_matrix(y_test, y_pred2)

In [87]:
y_predknn = model2.predict(MB)

#prints the prediction of the class
print(y_predknn)

[1]


# Logistic Regression

In [88]:
from sklearn.linear_model import LogisticRegression
model3 = LogisticRegression(random_state = 0)
model3.fit(x_train, y_train)

LogisticRegression(random_state=0)

In [89]:
y_pred3 = model3.predict(x_test)

In [90]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred3)
recall_sensitivity = metrics.recall_score(y_test,y_pred3, pos_label=1)
recall_specificity= metrics.recall_score(y_test, y_pred3, pos_label=0)
# print ("Confusion Matrix : \n", cm)
print("Testing Accuracy ",accuracy_score(y_test,y_pred3)*100)
print("Training Accuracy ",accuracy_score(y_train,model3.predict(x_train))*100)
print("Precision Score:",metrics.precision_score(y_test, y_pred3))
print("Recall Score:",metrics.recall_score(y_test, y_pred3))
print("F1 Score:",metrics.f1_score(y_test, y_pred3))
print("Sensitivity:",recall_sensitivity)
print("Specificity:",recall_specificity)

Testing Accuracy  82.40589198036007
Training Accuracy  79.90587272355228
Precision Score: 0.8135313531353136
Recall Score: 0.8285714285714286
F1 Score: 0.8209825145711906
Sensitivity: 0.8285714285714286
Specificity: 0.8197767145135566


In [91]:
y_predlr = model3.predict(MB)

#prints the prediction of the class
print(y_predlr)

[1]


# Testing on 100 Images

In [115]:
foldertest = r"D:\CV_datasets\370x370\crowded-test"
i=0
test = []
for filename in os.listdir(foldertest):
    #path
    path=os.path.join(foldertest,filename)
    img=cv2.imread(path)
    if img is None:
        continue
    resize=(100,300)

    #resize image
    img=cv2.resize(img,resize)
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

    #initialise sift descriptor
    sift = cv2.SIFT_create()
    keypoints, descriptors = sift.detectAndCompute(gray, None)
      
    #convert the descriptor array into a dataframe format
    out=pd.DataFrame(descriptors)
    print("descriptor shape ",i," : ", out.shape)

    #train the model for the features i.e. for all elements in the Dataframe
    array_double = np.array(out, dtype=np.double)
    if(array_double.any()==0):
        continue
    a = kmeans.predict(array_double)

    #get the values of the histogram for one image only for 5 clusters i.e. in 5 bins
    #kmeans.labels_ give us the label vlaue of the feature that its clustered into
    #hist will give the histogram for all those vlaues
    hist = np.histogram(a,bins=[0,1,2,3,4,5])

    #append the dataframe into the array in append mode, the array will only have 5 values which will store the values in a row
    test.append(hist[0])
    norm = Normalizer()
    normalized = norm.fit_transform(test)
    i=i+1

Output = pd.DataFrame(test)
#print("Histogram:\n",Output)
Output_trans = DhoniS.transform(Output)
#print(Output_trans.shape, Output_trans)
pcaOutput = pca.transform(Output_trans)
#print(pcaOutput.shape, pcaOutput)
model6.predict(pcaOutput)

descriptor shape  0  :  (258, 128)
descriptor shape  1  :  (151, 128)
descriptor shape  2  :  (280, 128)
descriptor shape  3  :  (64, 128)
descriptor shape  4  :  (96, 128)
descriptor shape  5  :  (81, 128)
descriptor shape  6  :  (302, 128)
descriptor shape  7  :  (39, 128)
descriptor shape  8  :  (220, 128)
descriptor shape  9  :  (109, 128)
descriptor shape  10  :  (47, 128)
descriptor shape  11  :  (211, 128)
descriptor shape  12  :  (215, 128)
descriptor shape  13  :  (0, 0)
descriptor shape  13  :  (51, 128)
descriptor shape  14  :  (95, 128)
descriptor shape  15  :  (349, 128)
descriptor shape  16  :  (70, 128)
descriptor shape  17  :  (86, 128)
descriptor shape  18  :  (151, 128)
descriptor shape  19  :  (291, 128)
descriptor shape  20  :  (87, 128)
descriptor shape  21  :  (60, 128)
descriptor shape  22  :  (0, 0)
descriptor shape  22  :  (39, 128)
descriptor shape  23  :  (88, 128)
descriptor shape  24  :  (296, 128)
descriptor shape  25  :  (200, 128)
descriptor shape  26  :

array([0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1,
       0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0,
       0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1,
       1, 0, 1, 0, 0, 1, 1, 1, 1, 1], dtype=int64)